//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdcControl.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdcControl.Resources.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acquisition duration (s):.
        /// </summary>
        public static string lblAcqDuration {
            get {
                return ResourceManager.GetString("lblAcqDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Averaging window size:.
        /// </summary>
        public static string lblAveraging {
            get {
                return ResourceManager.GetString("lblAveraging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port name:.
        /// </summary>
        public static string lblPortName {
            get {
                return ResourceManager.GetString("lblPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User opted to proceed after an unhandled exception..
        /// </summary>
        public static string msgExceptionOverride {
            get {
                return ResourceManager.GetString("msgExceptionOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected port name is invalid!.
        /// </summary>
        public static string msgInvalidPortSetting {
            get {
                return ResourceManager.GetString("msgInvalidPortSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t parse following data:.
        /// </summary>
        public static string msgParsingProblem {
            get {
                return ResourceManager.GetString("msgParsingProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The port is already open, reopening..
        /// </summary>
        public static string msgPortAlreadyOpen {
            get {
                return ResourceManager.GetString("msgPortAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t close the port!.
        /// </summary>
        public static string msgPortCloseProblem {
            get {
                return ResourceManager.GetString("msgPortCloseProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t open serial port!.
        /// </summary>
        public static string msgPortOpenProblem {
            get {
                return ResourceManager.GetString("msgPortOpenProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port write error!.
        /// </summary>
        public static string msgPortWriteError {
            get {
                return ResourceManager.GetString("msgPortWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string strCancelButton {
            get {
                return ResourceManager.GetString("strCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear screen.
        /// </summary>
        public static string strClearScreenButton {
            get {
                return ResourceManager.GetString("strClearScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection configuration.
        /// </summary>
        public static string strConfigButton {
            get {
                return ResourceManager.GetString("strConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string strConnectButton {
            get {
                return ResourceManager.GetString("strConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        public static string strDisconnectButton {
            get {
                return ResourceManager.GetString("strDisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export data as CSV.
        /// </summary>
        public static string strExportButton {
            get {
                return ResourceManager.GetString("strExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string strOKButton {
            get {
                return ResourceManager.GetString("strOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start recording.
        /// </summary>
        public static string strStartButton {
            get {
                return ResourceManager.GetString("strStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop recording.
        /// </summary>
        public static string strStopButton {
            get {
                return ResourceManager.GetString("strStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Acquisition in progress....
        /// </summary>
        public static string stsAcqInProgress {
            get {
                return ResourceManager.GetString("stsAcqInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device connected..
        /// </summary>
        public static string stsConnected {
            get {
                return ResourceManager.GetString("stsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting....
        /// </summary>
        public static string stsConnecting {
            get {
                return ResourceManager.GetString("stsConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong. Check the log for details..
        /// </summary>
        public static string stsFailure {
            get {
                return ResourceManager.GetString("stsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready..
        /// </summary>
        public static string stsReady {
            get {
                return ResourceManager.GetString("stsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting acquisition....
        /// </summary>
        public static string stsStartingAcq {
            get {
                return ResourceManager.GetString("stsStartingAcq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopping acquisition....
        /// </summary>
        public static string stsStoppingAcq {
            get {
                return ResourceManager.GetString("stsStoppingAcq", resourceCulture);
            }
        }
    }
}
